---

- name: restart postfix
  service: name=postfix state=restarted

- name: restart apache
  service: name=apache2 state=restarted

- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: restart pureftpd
  service: name=pure-ftpd state=restarted
